#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64
"a23zafar/07099589@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle12c.scs.ryerson.ca)
(Port=1521))(CONNECT_DATA=(SID=orcl12c)))" <<EOF
DROP TABLE AUTHOR CASCADE CONSTRAINTS;
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE BOOK_FINE CASCADE CONSTRAINTS;
DROP TABLE CAN_CONTAIN CASCADE CONSTRAINTS;
DROP TABLE LIBRARYBRANCH CASCADE CONSTRAINTS;
DROP TABLE LOAN CASCADE CONSTRAINTS;
DROP TABLE PART_OF CASCADE CONSTRAINTS;
DROP TABLE PUBLISHED CASCADE CONSTRAINTS;
DROP TABLE STUDENT CASCADE CONSTRAINTS;
DROP TABLE UNIVERSITY_ADMIN CASCADE CONSTRAINTS;
exit;
EOF